name: ubuntu build

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup variables
        run: |
          echo RELEASE=$(date +%Y\/%m\/%d) >> $GITHUB_ENV

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install make cmake gcc

      - name: install bfdev
        run: |
          git clone https://github.com/openbfdev/bfdev.git
          cd bfdev
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=${HOME}/.local \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build build --config ${{env.BUILD_TYPE}} \
            -j$(nproc) -- install

      - name: configure cmake
        run: |
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=${PWD}/install \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: build project
        run: |
          export C_INCLUDE_PATH=${C_INCLUDE_PATH}:${HOME}/.local/include
          export LIBRARY_PATH=${LIBRARY_PATH}:${HOME}/.local/lib:${HOME}/.local/lib64
          cmake --build build --config ${{env.BUILD_TYPE}} \
            -j$(nproc) -- install

      - name: create release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          body: ${{env.RELEASE}}
          tag_name: ${{env.RELEASE}}
          draft: false
          prerelease: false
          files: |
            ${{github.workspace}}/install/bin/brainfuck

      - name: delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          keep_latest: 1
          delete_tags: true
